### ISSUE TITLE
"defaults.ini" not in source

### ISSUE THREAD

**Issue by animafps** [couleur-tweak-tips/smoothie-rs#4]

**Comment by couleurm** [comment]
yes this is a design flaw I need to fix and is not really contributor-friendly, let me know if you've heard of a way to output the compiled binary to a custom directory after a cargo build/run is done whether it's a release or debug build

Please put these two files in the /target/debug/ directory, do not forget to rename them to .ini as that's what smoothie-rs is looking for in it's paths (GitHub is having a skill issue so I had to rename the extension)

[defaults.txt](https://github.com/couleur-tweak-tips/smoothie-rs/files/10610504/defaults.txt)
[recipe.txt](https://github.com/couleur-tweak-tips/smoothie-rs/files/10610503/recipe.txt)

defaults.ini is [loaded](https://github.com/couleur-tweak-tips/smoothie-rs/blob/fbca9d4840bc76906262a12669af712663bdd4dc/src/recipe.rs#L106-L107) into a hashmap, and then recipe.ini overrides all of it's existing values, this means:
* Empty values won't throw because they'd be null, defaults would be a backup
* People that are overwhelmed by all options can hand pick what they don't want to see
* Having a second recipe as a backup is convenient if you want to reset it (gotta implement `--reset-recipe`👀)

defaults.ini would have the "read only" attribute on windows to prevent accidental changes to that file

![image](https://user-images.githubusercontent.com/82747632/216809602-6f4ae7df-12f0-40fd-a62d-e2abf48021f8.png)

Let me know your thoughts on this choice

**Comment by couleurm** [comment]
now in [/target/](https://github.com/couleur-tweak-tips/smoothie-rs/tree/main/target)
